language: android
sudo: false
jdk:
  - oraclejdk8
android:
    components:
        - platform-tools
        - tools
        - build-tools-25.0.2
        - android-25
        - extra-android-m2repository
script:
    - cd BlinkInputDemo
    - ./gradlew clean :BlinkInputCombination:assembleRelease
    - ./gradlew clean :BlinkInputDetectorDemo:assembleRelease
    - ./gradlew clean :BlinkInputDirectAPI:assembleRelease
    - ./gradlew clean :BlinkInputFullScreen:assembleRelease
    - ./gradlew clean :BlinkInputRandomScanDemo:assembleRelease
    - ./gradlew clean :BlinkInputSegmentDemo:assembleRelease