language: android
sudo: false
android:
    components:
        - build-tools-23.0.0
        - android-23
        - extra-android-m2repository
script:
    - cd BlinkOCRDemo
    - ./gradlew clean assembleRelease